# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.3.dev21+g0ba63a4.d20230830'
__version_tuple__ = version_tuple = (1, 3, 'dev21', 'g0ba63a4.d20230830')
